CREATE TABLE matricula(
	codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
	dataCriacao DATE DEFAULT CURRENT_DATE,
	turno VARCHAR(6) NOT NULL CHECK(turno IN('manhã', 'tarde')),
	turma VARCHAR(10) NOT NULL,
	ano NUMBER NOT NULL,
	observacoes VARCHAR(50) DEFAULT ''
);

CREATE TABLE aluno(
    matricula NUMBER PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    certNasc NUMBER NOT NULL UNIQUE,
    dataNasc DATE NOT NULL,
    CONSTRAINT FK_aluno_matricula
    FOREIGN KEY (matricula)
    REFERENCES matricula(codigo)
     ON DELETE CASCADE
);

CREATE TABLE responsavel(
    codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nome varchar(50) NOT NULL,
    cpf varchar(11) NOT NULL UNIQUE,
    dataNasc DATE NOT NULL,
    telefone varchar(8) DEFAULT '',
    celular varchar(9) DEFAULT '',
    descricaoCorporal varchar(50) NOT NULL
);

CREATE TABLE responsavelAluno (
    codigoResponsavel NUMBER,
    matriculaAluno NUMBER,
    responsavelFinanceiro NUMBER(1,0) DEFAULT 0,
    CONSTRAINT PK_responsavelAluno
    PRIMARY KEY (codigoResponsavel, matriculaAluno),
    CONSTRAINT FK_responsavelAluno_responsavel
    FOREIGN KEY (codigoResponsavel)
    REFERENCES responsavel(codigo)
        ON DELETE CASCADE,
    CONSTRAINT FK_responsavelAluno_aluno
    FOREIGN KEY (matriculaAluno)
    REFERENCES aluno(matricula)
        ON DELETE CASCADE
);

CREATE TABLE endereco(
    codigo NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    cep VARCHAR(8) NOT NULL,
    estado VARCHAR(2) NOT NULL,
    cidade VARCHAR(50) NOT NULL,
    numero NUMBER NOT NULL,
    logradouro VARCHAR(50) NOT NULL,
    complemento VARCHAR(50) DEFAULT ''
);

CREATE TABLE enderecoResponsavel(
    codigoResponsavel NUMBER,
    codigoEndereco NUMBER,
    CONSTRAINT PK_enderecoResponsavel 
    PRIMARY KEY(codigoResponsavel, codigoEndereco),
    CONSTRAINT FK_enderecoResponsavel_responsavel
    FOREIGN KEY (codigoResponsavel)
    REFERENCES responsavel(codigo)
        ON DELETE CASCADE,
    CONSTRAINT FK_enderecoResponsavel_endereco
    FOREIGN KEY (codigoEndereco)
    REFERENCES endereco(codigo)
        ON DELETE CASCADE
);

CREATE TABLE enderecoAluno(
    matriculaAluno NUMBER,
    codigoEndereco NUMBER,
    CONSTRAINT PK_enderecoAluno
    PRIMARY KEY(matriculaAluno, codigoEndereco),
    CONSTRAINT FK_enderecoAluno_aluno
    FOREIGN KEY (matriculaAluno)
    REFERENCES aluno(matricula)
        ON DELETE CASCADE,
    CONSTRAINT FK_enderecoAluno_endereco
    FOREIGN KEY (codigoEndereco)
    REFERENCES endereco(codigo)
        ON DELETE CASCADE
);

CREATE TABLE deficiencia(
    matricula NUMBER,
    descricao VARCHAR(50) CHECK(descricao IN ('deficiência A', 'deficiência B', 'deficiência C')),
    CONSTRAINT PK_deficiencia
    PRIMARY KEY (matricula, descricao),
    CONSTRAINT FK_deficiencia_aluno
    FOREIGN KEY (matricula)
    REFERENCES aluno(matricula)
        ON DELETE CASCADE
);

CREATE TABLE remedio(
    matricula NUMBER,
    descricao VARCHAR(50) CHECK(descricao IN ('remédio A', 'remédio B', 'remédio C')),
    CONSTRAINT PK_remedio
    PRIMARY KEY (matricula, descricao),
    CONSTRAINT FK_remedio_aluno
    FOREIGN KEY (matricula)
    REFERENCES aluno(matricula)
        ON DELETE CASCADE
);
